dir.ask = 1  # 0: given, 1: ask
anchor.name = 'bet'
anchor.value = [-0.5, 0.0, 1.0, 2.0]
anchor.variable = 'q'
anchor.limit.name = "chu"
anchor.limit.value = 10
anchor.fix.name = "pin"
anchor.fix.target = "chu"
target = -1.0
num = 5
step = 0.01